# Author: https://github.com/electronicsleep
# Date: 07/20/2017
# Purpose: Ansible - Check Apt updates and log details to a file
# Released under the BSD license

# Get Date
- name: issue.net for os
  shell: date +%Y%m%d-%H%M
  register: date_contents

- debug: var=date_contents.stdout_lines

# Copy Update Script
- copy:
    src: update.sh
    dest: /tmp/update.sh

# Get OS
- name: issue.net for os
  shell: cat /etc/issue.net
  register: issue_contents

- debug: var=issue_contents.stdout_lines

# Get Kernel
- name: uname -a for kernel
  shell: uname -a | cut -f 3 -d " "
  register: uname_contents

- debug: var=uname_contents.stdout_lines

# Run Update Script
- name: run command to check for updates
  shell: bash -x /tmp/update.sh
  register: update_contents

- debug: var=update_contents.stdout_lines

# Run Update Check and Log details
- name: check updates info
  shell: cat /tmp/apt-update.log
  register: apt_updates_check

#- debug: var=apt_updates_check.stdout_lines

# Copy Apt update log to local
#- fetch:
#    dest: .
#    src: /tmp/apt-update.log

# Run Updates if found pending
- name: run updates
  shell: apt-get upgrade -y
  become: true
  become_user: root
  register: update_contents
  when: apt_updates_check.stdout.find("UPDATES PENDING") != -1

#- debug: var=update_contents.stdout_lines
